/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javafmt;

import org.junit.Test;
import static org.junit.Assert.assertTrue;

import javafmt.config.Config;
import javafmt.io.UnformattedStringUnit;
import static javafmt.config.JavaVersion.JAVA_11;

public class LibraryTest {
  @Test
  public void someLibraryMethodReturnsTrue() {
    var input = UnformattedStringUnit.of("class Foo {}");
    var config = Config.builder().indentation(2).javaVersion(JAVA_11).build();
    var res = Formatter.format(input, config);

    assertTrue("Successfully formatted simple input", res.successful());
  }
}
